[package]
name = "todolist"
version = "0.1.0"
authors = ["t3m8ch"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
